/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import member.member; 

/**
 *
 * @author Kahfi
 */
public class loginPenggguna extends javax.swing.JFrame {
    String IDmember, namaLengkap; 

    /**
     * Creates new form loginPenggguna
     */
    public loginPenggguna() {
        initComponents();
        
        
    }
    
    public void komponen(){
        IDmember = fieldID.getText().trim(); 
        namaLengkap = fieldNamaLengkap.getText().trim(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLoginAnggota = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Pengguna");
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelLoginAnggota.setBackground(new java.awt.Color(255, 255, 255));
        PanelLoginAnggota.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldNamaLengkap.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fieldNamaLengkap.setForeground(new java.awt.Color(153, 153, 153));
        fieldNamaLengkap.setText("Masukan nama lengkap");
        fieldNamaLengkap.setBorder(null);
        fieldNamaLengkap.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldNamaLengkapFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNamaLengkapFocusLost(evt);
            }
        });
        fieldNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaLengkapActionPerformed(evt);
            }
        });
        fieldNamaLengkap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldNamaLengkapKeyReleased(evt);
            }
        });
        PanelLoginAnggota.add(fieldNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 200, 20));

        fieldID.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fieldID.setForeground(new java.awt.Color(153, 153, 153));
        fieldID.setText("Masukan ID member");
        fieldID.setBorder(null);
        fieldID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fieldIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldIDFocusLost(evt);
            }
        });
        fieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIDActionPerformed(evt);
            }
        });
        fieldID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldIDKeyReleased(evt);
            }
        });
        PanelLoginAnggota.add(fieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("<html>\n<u>\ndaftar\n</u>\n</html>");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });
        PanelLoginAnggota.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 40, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Belum punya akun?");
        PanelLoginAnggota.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Lakukan Login untuk melihat penawaran");
        PanelLoginAnggota.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Paket Laundry");
        PanelLoginAnggota.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("atau");
        PanelLoginAnggota.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, -1, -1));

        kButton2.setText("LogIn");
        kButton2.setBorderPainted(false);
        kButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(66, 95, 235));
        kButton2.setkEndColor(new java.awt.Color(66, 95, 235));
        kButton2.setkHoverEndColor(new java.awt.Color(45, 182, 186));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(45, 182, 186));
        kButton2.setkPressedColor(new java.awt.Color(66, 95, 235));
        kButton2.setkSelectedColor(new java.awt.Color(66, 95, 235));
        kButton2.setkStartColor(new java.awt.Color(66, 95, 235));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        PanelLoginAnggota.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 380, 250, 30));

        kButton1.setBackground(new java.awt.Color(66, 95, 235));
        kButton1.setText("Kembali ke halaman sebelumnya");
        kButton1.setBorderPainted(false);
        kButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        kButton1.setkBackGroundColor(new java.awt.Color(66, 95, 235));
        kButton1.setkEndColor(new java.awt.Color(66, 95, 235));
        kButton1.setkHoverEndColor(new java.awt.Color(45, 182, 186));
        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton1.setkHoverStartColor(new java.awt.Color(45, 182, 186));
        kButton1.setkPressedColor(new java.awt.Color(66, 95, 235));
        kButton1.setkSelectedColor(new java.awt.Color(66, 95, 235));
        kButton1.setkStartColor(new java.awt.Color(66, 95, 235));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        PanelLoginAnggota.add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 600, 200, 30));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        PanelLoginAnggota.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 320, 20, 40));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Login Pengguna");
        PanelLoginAnggota.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 210, 150, 40));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/id.png"))); // NOI18N
        PanelLoginAnggota.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, 20, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg login res.png"))); // NOI18N
        jLabel1.setText(" ");
        PanelLoginAnggota.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 660));

        getContentPane().add(PanelLoginAnggota, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamaLengkapFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaLengkapFocusGained
        // TODO add your handling code here:
        if (fieldNamaLengkap.getText().equals("Masukan nama lengkap")) {
            fieldNamaLengkap.setText("");
            fieldNamaLengkap.setForeground(Color.black);
        }
    }//GEN-LAST:event_fieldNamaLengkapFocusGained

    private void fieldNamaLengkapFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNamaLengkapFocusLost
        // TODO add your handling code here:
        if (fieldNamaLengkap.getText().equals("")) {
            fieldNamaLengkap.setText("Masukan nama lengkap");
            fieldNamaLengkap.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_fieldNamaLengkapFocusLost

    private void fieldNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaLengkapActionPerformed

    private void fieldNamaLengkapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldNamaLengkapKeyReleased

    }//GEN-LAST:event_fieldNamaLengkapKeyReleased

    private void fieldIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldIDFocusGained
        if(fieldID.getText().equals("Masukan ID member")){
            fieldID.setText("");
            fieldID.setForeground(Color.black);
        }
    }//GEN-LAST:event_fieldIDFocusGained

    private void fieldIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldIDFocusLost
          if (fieldID.getText().equals("")) {
            fieldID.setText("Masukan ID member");
            fieldID.setForeground(new Color(153, 153, 153));
          }
    }//GEN-LAST:event_fieldIDFocusLost

    private void fieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDActionPerformed

    private void fieldIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIDKeyReleased

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
     komponen();
        
      if(IDmember.equals("Masukan ID member")){
         JOptionPane.showMessageDialog(null, "ID member tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
      }else if(namaLengkap.equals("Masukan nama lengkap")){
         JOptionPane.showMessageDialog(null, "Nama lengkap tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
      }else{
          try {
              Connection con = koneksi.getKoneksi(); 
              String sql = "select * from tb_member where id_member ='" + IDmember + "'and nama ='" + namaLengkap + "'"; 
              PreparedStatement pst = con.prepareStatement(sql); 
              ResultSet set = pst.executeQuery(sql); 
              if(set.next()){
                 if(!IDmember.equals(set.getString("id_member")) && !namaLengkap.equals(set.getString("nama"))){
                  JOptionPane.showMessageDialog(null, "nama atau ID salah!", "Error", JOptionPane.ERROR_MESSAGE);
                     
                 }else{
                  JOptionPane.showMessageDialog(null, "Login Sukses", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                     
                 }
                
              }else {
                  JOptionPane.showMessageDialog(null, "Login Gagal!", "Error", JOptionPane.ERROR_MESSAGE);
                  
              }
              
          } catch (Exception e) {
              JOptionPane.showMessageDialog(null, e);
              
          }
      }
        
    

    }//GEN-LAST:event_kButton2ActionPerformed

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
     new member().setVisible(true);
     
    }//GEN-LAST:event_jLabel3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginPenggguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginPenggguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginPenggguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginPenggguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginPenggguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelLoginAnggota;
    public static final javax.swing.JTextField fieldID = new javax.swing.JTextField();
    public static final javax.swing.JTextField fieldNamaLengkap = new javax.swing.JTextField();
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private com.k33ptoo.components.KButton kButton1;
    private com.k33ptoo.components.KButton kButton2;
    // End of variables declaration//GEN-END:variables
}
