/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member;
import DashboardAdmin.Admin;
import checkbox.JCheckBoxCustom;
import com.k33ptoo.components.KButton;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import static member.member.OpsiPerempuan;
import static member.member.fieldAlamat;
import static member.member.fieldIDMember;
import static member.member.fieldNamaLengkap;
import static member.member.fieldTelepon;
import static member.member.opsiLakiLaki;
import textfield.TextField;

/**
 *
 * @author Kahfi
 */
public class editMember extends javax.swing.JFrame {
    String IDmember, namaLengkap, alamat, jenisKelamin, telepon;
    String labelPelanggan;
    String buttonPelanggan; 
    /**
     * Creates new form editMember
     */
    public editMember() {
        initComponents();
    }
    
     public void komponen() {
        IDmember = fieldIDMember.getText();
        namaLengkap = fieldNamaLengkap.getText();
        alamat = fieldAlamat.getText();

        try {
            if (opsiLakiLaki.isSelected()) {
                jenisKelamin = opsiLakiLaki.getText();
            } else if (OpsiPerempuan.isSelected()) {
                jenisKelamin = OpsiPerempuan.getText();
            } else {
                jenisKelamin = "";
            }

        } catch (Exception e) {
        }

        telepon = fieldTelepon.getText();

    }
     
//      public void setTitlePelanggan(String labelPelanggan) {
//       this.labelPelanggan = labelPelanggan; 
//    }
//
//    
//    
//    
//
//    public void setIDmember(String IDmember) {
//        this.IDmember = IDmember;
//    }
//
//    public void setdNamaLengkap(String namaLengkap) {
//        this.namaLengkap = namaLengkap;
//    }
//
//    public  void setAlamat(String alamat) {
//        this.alamat = alamat; 
//    }
//
//    public void setCheckBoxLaki(String jenisKelamin) {
//       this.jenisKelamin = jenisKelamin; 
//    }
//
//    public  void setCheckPerempuan(String jenisKelamin) {
//        this.jenisKelamin = jenisKelamin; 
//    }
//    
//    
//
//
//    public void setTelepon(String telepon) {
//        this.telepon = telepon;
//    }
//
//    public void setButtonPelanggan(String buttonPelanggan) {
//        this.buttonPelanggan = buttonPelanggan;
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldAlamat = new textfield.TextField();
        fieldNamaLengkap = new textfield.TextField();
        fieldIDMember = new textfield.TextField();
        buttonPerbarui = new com.k33ptoo.components.KButton();
        titlePelanggan = new javax.swing.JLabel();
        opsiLakiLaki = new checkbox.JCheckBoxCustom();
        OpsiPerempuan = new checkbox.JCheckBoxCustom();
        jLabel1 = new javax.swing.JLabel();
        fieldTelepon = new textfield.TextField();
        Hapus = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Perbarui Pelanggan");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/man_1.png"))); // NOI18N

        fieldAlamat.setLabelText("Alamat");

        fieldNamaLengkap.setLabelText("Nama Lengkap");

        fieldIDMember.setLabelText("ID Member");
        fieldIDMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldIDMemberMouseClicked(evt);
            }
        });

        buttonPerbarui.setText("Perbarui");
        buttonPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPerbarui.setIconTextGap(5);
        buttonPerbarui.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buttonPerbarui.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkPressedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkSelectedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkStartColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerbaruiActionPerformed(evt);
            }
        });

        titlePelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePelanggan.setText("Perbarui Pelanggan");

        opsiLakiLaki.setForeground(new java.awt.Color(102, 102, 102));
        opsiLakiLaki.setText("L");

        OpsiPerempuan.setForeground(new java.awt.Color(102, 102, 102));
        OpsiPerempuan.setText("P");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Jenis Kelamin");

        fieldTelepon.setLabelText("Telepon");

        Hapus.setText("Hapus");
        Hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Hapus.setIconTextGap(5);
        Hapus.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        Hapus.setkEndColor(new java.awt.Color(102, 102, 255));
        Hapus.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        Hapus.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        Hapus.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        Hapus.setkPressedColor(new java.awt.Color(153, 153, 255));
        Hapus.setkSelectedColor(new java.awt.Color(153, 153, 255));
        Hapus.setkStartColor(new java.awt.Color(153, 153, 255));
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(opsiLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(OpsiPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(fieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(titlePelanggan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(164, 164, 164))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(titlePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opsiLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpsiPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(fieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIDMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldIDMemberMouseClicked
        JOptionPane.showMessageDialog(null, "ID Member dibuat secara otomatis dan tidak bisa diedit", "From Admin", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_fieldIDMemberMouseClicked

    private void buttonPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerbaruiActionPerformed
        komponen();
        
        try {
            String sql = "update tb_member set nama = '" + namaLengkap + "', alamat='" + alamat + "', jenis_kelamin = '" + jenisKelamin + 
                    "', tlp = '" + telepon + "'where id_member = '" + IDmember + "'"; 
            Connection con = koneksi.getKoneksi(); 
            PreparedStatement pst = con.prepareStatement(sql); 
            pst.execute(); 
            dispose();
            JOptionPane.showMessageDialog(null, "Data Berhasil DiUbah, Silahkan Refresh!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    
    }//GEN-LAST:event_buttonPerbaruiActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        komponen();
        int opsi = JOptionPane.showConfirmDialog(null, "Hapus data pelanggan atas nama : " + namaLengkap, "Peringatan", JOptionPane.WARNING_MESSAGE); 
        if(opsi==0){
            try {
                String sql = "delete from tb_member where id_member ='" + IDmember + "'"; 
                Connection con = koneksi.getKoneksi(); 
                PreparedStatement pst = con.prepareStatement(sql); 
                pst.execute();
                dispose();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus, Silahkan Refresh!");
                
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_HapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.k33ptoo.components.KButton Hapus;
    public static checkbox.JCheckBoxCustom OpsiPerempuan;
    public static com.k33ptoo.components.KButton buttonPerbarui;
    public static textfield.TextField fieldAlamat;
    public static textfield.TextField fieldIDMember;
    public static textfield.TextField fieldNamaLengkap;
    public static textfield.TextField fieldTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static checkbox.JCheckBoxCustom opsiLakiLaki;
    public static javax.swing.JLabel titlePelanggan;
    // End of variables declaration//GEN-END:variables
}
