/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member;

import DashboardAdmin.Admin;
import checkbox.JCheckBoxCustom;
import com.k33ptoo.components.KButton;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import textfield.TextField;

/**
 *
 * @author Kahfi
 */
public class member extends javax.swing.JFrame {

    String IDmember, namaLengkap, alamat, jenisKelamin, telepon;
    String labelPelanggan;
    String buttonPelanggan; 
    /**
     * Creates new form member
     */
    public member() {
        initComponents();
        autoNumber();

    }

    public void komponen() {
        IDmember = fieldIDMember.getText();
        namaLengkap = fieldNamaLengkap.getText();
        alamat = fieldAlamat.getText();

        try {
            if (opsiLakiLaki.isSelected()) {
                jenisKelamin = opsiLakiLaki.getText();
            } else if (OpsiPerempuan.isSelected()) {
                jenisKelamin = OpsiPerempuan.getText();
            } else {
                jenisKelamin = "";
            }

        } catch (Exception e) {
        }

        telepon = fieldTelepon.getText();

    }

    public void autoNumber() {
        try {
            String sql = "select max(id_member) from tb_member";
            Connection con = koneksi.getKoneksi();
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet set = pst.executeQuery(sql);
            if (set.next()) {

                int IDmember = set.getInt(1);
                // nilai 1 diberikan untuk mengidikasikan field ID number pada database yang terdapat pada urutan satu
                fieldIDMember.setText(Integer.toString(IDmember + 1));
                fieldIDMember.setEditable(false);

            } else {

            }
        } catch (Exception e) {
        }

    }

//    public void setTitlePelanggan(String labelPelanggan) {
//       this.labelPelanggan = labelPelanggan; 
//    }
//
//    
//    
//    
//
//    public void setIDmember(String IDmember) {
//        this.IDmember = IDmember;
//    }
//
//    public void setdNamaLengkap(String namaLengkap) {
//        this.namaLengkap = namaLengkap;
//    }
//
//    public  void setAlamat(String alamat) {
//        this.alamat = alamat; 
//    }
//
//    public void setCheckBoxLaki(String jenisKelamin) {
//       this.jenisKelamin = jenisKelamin; 
//    }
//
//    public  void setCheckPerempuan(String jenisKelamin) {
//        this.jenisKelamin = jenisKelamin; 
//    }
//    
//    
//
//
//    public void setTelepon(String telepon) {
//        this.telepon = telepon;
//    }
//
//    public void setButtonPelanggan(String buttonPelanggan) {
//        this.buttonPelanggan = buttonPelanggan;
//    }
    
    
    
    
    
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelMember = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        fieldAlamat = new textfield.TextField();
        fieldNamaLengkap = new textfield.TextField();
        fieldIDMember = new textfield.TextField();
        button = new com.k33ptoo.components.KButton();
        titlePelanggan = new javax.swing.JLabel();
        opsiLakiLaki = new checkbox.JCheckBoxCustom();
        OpsiPerempuan = new checkbox.JCheckBoxCustom();
        jLabel1 = new javax.swing.JLabel();
        fieldTelepon = new textfield.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pelanggan");

        panelMember.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/man_1.png"))); // NOI18N

        fieldAlamat.setLabelText("Alamat");

        fieldNamaLengkap.setLabelText("Nama Lengkap");

        fieldIDMember.setLabelText("ID Member");
        fieldIDMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldIDMemberMouseClicked(evt);
            }
        });

        button.setText("Buat");
        button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button.setIconTextGap(5);
        button.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        button.setkEndColor(new java.awt.Color(102, 102, 255));
        button.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        button.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        button.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        button.setkPressedColor(new java.awt.Color(153, 153, 255));
        button.setkSelectedColor(new java.awt.Color(153, 153, 255));
        button.setkStartColor(new java.awt.Color(153, 153, 255));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        titlePelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePelanggan.setText("Data Pelanggan");

        buttonGroup1.add(opsiLakiLaki);
        opsiLakiLaki.setForeground(new java.awt.Color(102, 102, 102));
        opsiLakiLaki.setText("L");

        buttonGroup1.add(OpsiPerempuan);
        OpsiPerempuan.setForeground(new java.awt.Color(102, 102, 102));
        OpsiPerempuan.setText("P");

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Jenis Kelamin");

        fieldTelepon.setLabelText("Telepon");

        javax.swing.GroupLayout panelMemberLayout = new javax.swing.GroupLayout(panelMember);
        panelMember.setLayout(panelMemberLayout);
        panelMemberLayout.setHorizontalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMemberLayout.createSequentialGroup()
                        .addComponent(opsiLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(OpsiPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addComponent(fieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMemberLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(titlePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMemberLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(152, 152, 152))
        );
        panelMemberLayout.setVerticalGroup(
            panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMemberLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(titlePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(panelMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opsiLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpsiPerempuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(fieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        komponen();

        if (namaLengkap.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nama Lengkap tidak boleh kosong!");

        } else if (alamat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Alamat tidak boleh kosong!");

        } else if (jenisKelamin.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukan jenis kelamin!");

        } else if (telepon.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No Telepon tidak boleh kosong!");

        } else {
            try {
                String sql = "insert into tb_member values ('" + IDmember + "','" + namaLengkap + "','" + alamat + "','" + jenisKelamin + "','" + telepon + "')";
                Connection con = koneksi.getKoneksi();
                PreparedStatement pst = con.prepareStatement(sql);
                pst.execute();
                dispose();
             
                JOptionPane.showMessageDialog(null, "Data Berhasil ditambah, Silahkan Refresh!");

            } catch (Exception e) {
            }

        }
    }//GEN-LAST:event_buttonActionPerformed

    private void fieldIDMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldIDMemberMouseClicked
        JOptionPane.showMessageDialog(null, "ID Member dibuat secara otomatis dan tidak bisa diedit", "From Admin", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_fieldIDMemberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static checkbox.JCheckBoxCustom OpsiPerempuan;
    public static com.k33ptoo.components.KButton button;
    private javax.swing.ButtonGroup buttonGroup1;
    public static textfield.TextField fieldAlamat;
    public static textfield.TextField fieldIDMember;
    public static textfield.TextField fieldNamaLengkap;
    public static textfield.TextField fieldTelepon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static checkbox.JCheckBoxCustom opsiLakiLaki;
    private javax.swing.JPanel panelMember;
    public static javax.swing.JLabel titlePelanggan;
    // End of variables declaration//GEN-END:variables
}
