package Transaksi;

import DashboardAdmin.Admin;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import koneksi.koneksi;

/**
 *
 * @author Kahfi
 */
public class DetailTransaksi extends javax.swing.JFrame {
    
    // ka lya bikin variabel  koneksi baru
    Connection con;
    PreparedStatement pst;
    ResultSet set;
    koneksi koneksi = new koneksi();
    
    
    
    
    
    
    
    

    String nomorTransaksi, IDTransaksi, IDPaket, namaPaket, keterangan;
    int hargaPaket;
    double jumlah;
    long totalBayar, nominalUang, kembalian;

    public DetailTransaksi() {
        initComponents();
        IDTransaksi();
        autoNomorTransaksi();
        namaPaket();

    }

    public void komponenDetailTransaksi() {
        this.nomorTransaksi = fieldNomorTransaksi.getText();
        this.IDTransaksi = comboIDTransaksi.getSelectedItem().toString();
        this.namaPaket = comboNamaPaket.getSelectedItem().toString();
        this.IDPaket = fieldIDPaket.getText();
        this.hargaPaket = Integer.valueOf(fieldHargaPaket.getText());
        this.jumlah = (double) fieldJumlah.getValue();

    }

    public void bersihkanTransaksi() {
        fieldNomorTransaksi.setText("");
        comboNamaPaket.setSelectedIndex(0);
        fieldHargaPaket.setText("");
        fieldIDPaket.setText("");
        comboIDTransaksi.setSelectedIndex(0);
        fieldTotalPembayaran.setText("");

    }

    public void IDTransaksi() {
        try {
            String sql = "select id_transaksi from tb_transaksi";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.set = pst.executeQuery();
            while (set.next()) {
                comboIDTransaksi.addItem(set.getString("id_transaksi"));

            }

        } catch (Exception e) {
        }
    }

    public void autoNomorTransaksi() {
        try {
            String sql = "select max(id) as nomorTransaksi from tb_detail_transaksi";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.set = pst.executeQuery();
            if (set.next()) {
                int nomorTransaksi = set.getInt("nomorTransaksi");
                fieldNomorTransaksi.setText(String.valueOf(nomorTransaksi + 2));
                fieldNomorTransaksi.setEnabled(false);

            }
        } catch (Exception e) {
        }
    }

    public void namaPaket() {

        try {
            String sql = "select nama_paket from tb_paket";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.set = pst.executeQuery();
            while (set.next()) {
                comboNamaPaket.addItem(set.getString("nama_paket"));
            }
        } catch (Exception e) {
        }
    }
    
    public void insertDataTransaksi(){
        komponenDetailTransaksi();
        try {
            String sql = "insert into tb_detail_transaksi values(?, ?, ?, ?, ?)";
            this.pst = koneksi.getKoneksi().prepareStatement(sql); 
            this.pst.setString(1, nomorTransaksi);
            this.pst.setString(2, IDTransaksi);
            this.pst.setString(3, IDPaket);
            this.pst.setDouble(4, jumlah);
            this.pst.setString(5, "Pesanan Laundry");
            this.pst.execute();
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
       public void updateStatusTransaksi(){
        komponenDetailTransaksi();
        try {
            String sql = "update tb_transaksi set bayar=? where id_transaksi=?";
            this.pst = koneksi.getKoneksi().prepareStatement(sql); 
            this.pst.setString(1, "sudah bayar");
            this.pst.setString(2, IDTransaksi);
            this.pst.executeUpdate(); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new test.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboIDTransaksi = new combobox.Combobox();
        jLabel1 = new javax.swing.JLabel();
        comboNamaPaket = new combobox.Combobox();
        jLabel2 = new javax.swing.JLabel();
        fieldNomorTransaksi = new textfield.TextField();
        fieldIDPaket = new textfield.TextField();
        fieldHargaPaket = new textfield.TextField();
        fieldJumlah = new spinner.Spinner();
        dashboard16 = new com.k33ptoo.components.KButton();
        fieldTotalPembayaran = new textfield.TextField();
        fieldKembalian = new textfield.TextField();
        dashboard17 = new com.k33ptoo.components.KButton();
        fieldNominalUang = new textfield.TextField();
        dashboard18 = new com.k33ptoo.components.KButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Decoration Bubble (1).png"))); // NOI18N
        panelRound1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Detail Transaksi Pembayaran");
        panelRound1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 310, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Decoration Bubble (1).png"))); // NOI18N
        panelRound1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 130, 50));

        comboIDTransaksi.setLabeText("");
        panelRound1.add(comboIDTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 280, 40));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("ID Paket");
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 110, -1));

        comboNamaPaket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih Paket" }));
        comboNamaPaket.setLabeText("");
        comboNamaPaket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboNamaPaketMouseClicked(evt);
            }
        });
        comboNamaPaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNamaPaketActionPerformed(evt);
            }
        });
        panelRound1.add(comboNamaPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 280, 40));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText(" Nama Paket");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, -1));

        fieldNomorTransaksi.setLabelText("Nomor Transaksi");
        panelRound1.add(fieldNomorTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 280, -1));

        fieldIDPaket.setLabelText("");
        panelRound1.add(fieldIDPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 280, -1));

        fieldHargaPaket.setLabelText("Harga Paket");
        panelRound1.add(fieldHargaPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 280, -1));

        fieldJumlah.setForeground(new java.awt.Color(204, 204, 255));
        fieldJumlah.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 10.0d, 1.0d));
        fieldJumlah.setLabelText("Jumlah Paket/KG");
        fieldJumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldJumlahMouseClicked(evt);
            }
        });
        fieldJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fieldJumlahKeyReleased(evt);
            }
        });
        panelRound1.add(fieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 250, 280, 50));

        dashboard16.setText("Hitung Pesanan");
        dashboard16.setToolTipText("");
        dashboard16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard16.setIconTextGap(15);
        dashboard16.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard16.setkBorderRadius(20);
        dashboard16.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard16.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard16.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard16.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard16ActionPerformed(evt);
            }
        });
        panelRound1.add(dashboard16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 280, -1));

        fieldTotalPembayaran.setLabelText("Total Pembayaran");
        panelRound1.add(fieldTotalPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 280, 50));

        fieldKembalian.setLabelText("Kembalian");
        panelRound1.add(fieldKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 280, 50));

        dashboard17.setText("Bayar");
        dashboard17.setToolTipText("");
        dashboard17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard17.setIconTextGap(15);
        dashboard17.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard17.setkBorderRadius(20);
        dashboard17.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard17.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard17.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard17.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard17ActionPerformed(evt);
            }
        });
        panelRound1.add(dashboard17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 280, -1));

        fieldNominalUang.setLabelText("Masukan Nominal Uang");
        panelRound1.add(fieldNominalUang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 280, 50));

        dashboard18.setText("Bersihkan Data");
        dashboard18.setToolTipText("");
        dashboard18.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard18.setIconTextGap(15);
        dashboard18.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard18.setkBorderRadius(20);
        dashboard18.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard18.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard18.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard18.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard18ActionPerformed(evt);
            }
        });
        panelRound1.add(dashboard18, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 280, -1));

        jLabel3.setBackground(new java.awt.Color(153, 153, 153));
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("ID Transaksi");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboNamaPaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNamaPaketActionPerformed
        String namaPaket = comboNamaPaket.getSelectedItem().toString();
        try {
            String sql = "select * from tb_paket where nama_paket=?";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.pst.setString(1, namaPaket);
            this.set = pst.executeQuery();
            if (set.next()) {
                fieldIDPaket.setText(set.getString("id_paket"));
                fieldIDPaket.setEnabled(false);

                fieldHargaPaket.setText(String.valueOf(set.getInt("harga")));
                fieldHargaPaket.setEditable(false);
            }

        } catch (Exception e) {
        }

    }//GEN-LAST:event_comboNamaPaketActionPerformed

    private void comboNamaPaketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboNamaPaketMouseClicked

    }//GEN-LAST:event_comboNamaPaketMouseClicked

    private void fieldJumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldJumlahMouseClicked

    }//GEN-LAST:event_fieldJumlahMouseClicked

    private void fieldJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJumlahKeyReleased

    }//GEN-LAST:event_fieldJumlahKeyReleased

    private void dashboard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard16ActionPerformed
        try {
            komponenDetailTransaksi();
            this.totalBayar = (long) (hargaPaket * jumlah);
            fieldTotalPembayaran.setText("Rp." + totalBayar);
            fieldTotalPembayaran.setEditable(false);
        } catch (Exception e) {
        }


    }//GEN-LAST:event_dashboard16ActionPerformed

    private void dashboard17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard17ActionPerformed
        try {
            nominalUang = Long.valueOf(fieldNominalUang.getText());
            this.kembalian = nominalUang - totalBayar;
            if(nominalUang < totalBayar){
                JOptionPane.showMessageDialog(null, "Uang Anda Kurang Rp." + kembalian, "Pesan dari admin", JOptionPane.INFORMATION_MESSAGE);
                this.kembalian = 0; 
                fieldKembalian.setText("Rp." + kembalian);
                
            }else {
                 this.kembalian = nominalUang - totalBayar;
                JOptionPane.showMessageDialog(null, "Terimakasih sudah berbelanja", "Pesan dari admin", JOptionPane.INFORMATION_MESSAGE);
                fieldKembalian.setText("Rp." + kembalian);
                insertDataTransaksi();
                updateStatusTransaksi();
              
                
            }
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_dashboard17ActionPerformed

    private void dashboard18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard18ActionPerformed
        // TODO add your handling code here:
        bersihkanTransaksi();
    }//GEN-LAST:event_dashboard18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static combobox.Combobox comboIDTransaksi;
    private combobox.Combobox comboNamaPaket;
    private com.k33ptoo.components.KButton dashboard16;
    private com.k33ptoo.components.KButton dashboard17;
    private com.k33ptoo.components.KButton dashboard18;
    private textfield.TextField fieldHargaPaket;
    private textfield.TextField fieldIDPaket;
    private spinner.Spinner fieldJumlah;
    private textfield.TextField fieldKembalian;
    private textfield.TextField fieldNominalUang;
    private textfield.TextField fieldNomorTransaksi;
    private textfield.TextField fieldTotalPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private test.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
