
package Transaksi;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author Kahfi
 */
public class EditDetailTransaksi extends javax.swing.JFrame {
    PreparedStatement pst; 
    ResultSet set; 
    koneksi koneksi = new koneksi(); 

    /**
     * Creates new form EditDetailTransaksi
     */
    public EditDetailTransaksi() {
        initComponents();
    }
    
    public void hapusDetailTransaksi(){
        try {
            String IDTransaksi = fieldIDTransaksi.getText(); 
            String sql = "delete from tb_detail_transaksi where id_transaksi=?";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.pst.setString(1, IDTransaksi);
            this.pst.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Transaksi Berhasil Dihapus", "Pesan Dari Admin", JOptionPane.WARNING_MESSAGE);
            this.dispose(); 
        } catch (Exception e) {
        }
        
    }
    
    public void updateProgresPesanan(){
        try {
            String IDTransaksi = fieldIDTransaksi.getText(); 
            String progresPesanan = comboProgresPesanan.getSelectedItem().toString(); 
            System.out.println(IDTransaksi);
            System.out.println(progresPesanan);
            String sql = "update tb_transaksi set status=? where id_transaksi=?"; 
            this.pst = koneksi.getKoneksi().prepareStatement(sql); 
            this.pst.setString(1, progresPesanan); 
            this.pst.setString(2, IDTransaksi);
            this.pst.executeUpdate(); 
            JOptionPane.showMessageDialog(null, "Progres Berhasil DiUpdate");
            this.dispose(); 
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dashboard18 = new com.k33ptoo.components.KButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fieldIDTransaksi = new textfield.TextField();
        fieldNamaPelanggan = new textfield.TextField();
        fieldBiayaAdmin = new textfield.TextField();
        fieldPajak = new textfield.TextField();
        fieldNamaPaket = new textfield.TextField();
        fieldDiskon = new textfield.TextField();
        fieldHargaPaket = new textfield.TextField();
        fieldStatusPesanan = new textfield.TextField();
        fieldJumlah = new textfield.TextField();
        dashboard16 = new com.k33ptoo.components.KButton();
        dashboard17 = new com.k33ptoo.components.KButton();
        comboProgresPesanan = new combobox.Combobox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboard18.setText("Lanjutkan Transaksi");
        dashboard18.setToolTipText("");
        dashboard18.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard18.setIconTextGap(15);
        dashboard18.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard18.setkBorderRadius(20);
        dashboard18.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard18.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard18.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard18.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard18.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard18ActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 160, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Decoration Bubble (1).png"))); // NOI18N
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 110, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Update Progres Pesanan");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 420, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/Decoration Bubble (1).png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 130, 50));

        fieldIDTransaksi.setLabelText("ID Transaksi");
        jPanel1.add(fieldIDTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 230, -1));

        fieldNamaPelanggan.setLabelText("Nama Pelanggan");
        jPanel1.add(fieldNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 230, -1));

        fieldBiayaAdmin.setLabelText("Biaya Admin ");
        jPanel1.add(fieldBiayaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, -1));

        fieldPajak.setLabelText("Pajak ");
        jPanel1.add(fieldPajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 230, -1));

        fieldNamaPaket.setLabelText("Nama Paket");
        jPanel1.add(fieldNamaPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 230, -1));

        fieldDiskon.setLabelText("Diskon ");
        jPanel1.add(fieldDiskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 230, -1));

        fieldHargaPaket.setLabelText("harga Paket");
        jPanel1.add(fieldHargaPaket, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 230, -1));

        fieldStatusPesanan.setLabelText("Status Pesanan");
        jPanel1.add(fieldStatusPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 230, -1));

        fieldJumlah.setLabelText("Jumlah");
        jPanel1.add(fieldJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 230, -1));

        dashboard16.setText("Hapus data");
        dashboard16.setToolTipText("");
        dashboard16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard16.setIconTextGap(15);
        dashboard16.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard16.setkBorderRadius(20);
        dashboard16.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard16.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard16.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard16.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard16.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard16ActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 230, -1));

        dashboard17.setText("Update Progres");
        dashboard17.setToolTipText("");
        dashboard17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        dashboard17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dashboard17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dashboard17.setIconTextGap(15);
        dashboard17.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        dashboard17.setkBorderRadius(20);
        dashboard17.setkEndColor(new java.awt.Color(51, 51, 255));
        dashboard17.setkHoverColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkHoverEndColor(new java.awt.Color(153, 102, 255));
        dashboard17.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        dashboard17.setkHoverStartColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkPressedColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkSelectedColor(new java.awt.Color(153, 153, 255));
        dashboard17.setkStartColor(new java.awt.Color(153, 153, 255));
        dashboard17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard17ActionPerformed(evt);
            }
        });
        jPanel1.add(dashboard17, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 230, -1));

        comboProgresPesanan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "baru ", "proses", "selesai", "diambil" }));
        comboProgresPesanan.setLabeText("Progres Pesanan");
        jPanel1.add(comboProgresPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 230, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 896, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboard18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard18ActionPerformed
       

    }//GEN-LAST:event_dashboard18ActionPerformed

    private void dashboard16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard16ActionPerformed
        String namaPelanggan = fieldNamaPelanggan.getText(); 
        int konfirmasi = JOptionPane.showConfirmDialog(null, "Hapus Data Transaksi " + namaPelanggan + "?", "Pesan Dari Admin", JOptionPane.WARNING_MESSAGE); 
        if(konfirmasi==0){
            hapusDetailTransaksi();
        }

    }//GEN-LAST:event_dashboard16ActionPerformed

    private void dashboard17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard17ActionPerformed
       updateProgresPesanan();
    }//GEN-LAST:event_dashboard17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDetailTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDetailTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static combobox.Combobox comboProgresPesanan;
    private com.k33ptoo.components.KButton dashboard16;
    private com.k33ptoo.components.KButton dashboard17;
    private com.k33ptoo.components.KButton dashboard18;
    public static textfield.TextField fieldBiayaAdmin;
    public static textfield.TextField fieldDiskon;
    public static textfield.TextField fieldHargaPaket;
    public static textfield.TextField fieldIDTransaksi;
    public static textfield.TextField fieldJumlah;
    public static textfield.TextField fieldNamaPaket;
    public static textfield.TextField fieldNamaPelanggan;
    public static textfield.TextField fieldPajak;
    public static textfield.TextField fieldStatusPesanan;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
