package outlet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.koneksi;

/**
 *
 * @author Kahfi
 */
public class TambahOutlet extends javax.swing.JFrame {

    String idOutlet, namaOutlet, alamatOutlet, teleponOutlet;
    Connection con;
    PreparedStatement pst;
    ResultSet set;
    koneksi koneksi = new koneksi();

    /**
     * Creates new form TambahOutlet
     */
    public TambahOutlet() {
        initComponents();
        autoNumberID();
    }

    public void autoNumberID() {
        try {
            String sql = "select max(id_outlet) as autoNumber from tb_outlet";
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            this.set = pst.executeQuery(sql); 
            if(set.next()){
                int autoNumber = set.getInt("autoNumber"); 
                fieldIDOutlet.setText(Integer.toString(autoNumber + 1));
                fieldIDOutlet.setEditable(false);
                
            }
        } catch (Exception e) {
        }

    }

    public void komponen() {
        this.idOutlet = fieldIDOutlet.getText();
        this.namaOutlet = fieldNamaOutlet.getText();
        this.alamatOutlet = fieldAlamatOutlet.getText();
        this.teleponOutlet = fieldTeleponOutlet.getText();
    }
    
    public void insertData(){
        komponen();
        try {
            String sql = "insert into tb_outlet values ('" + idOutlet + "','" + namaOutlet + "','" + alamatOutlet + "','" + teleponOutlet + "')"; 
            this.pst = koneksi.getKoneksi().prepareStatement(sql); 
            pst.execute();
            this.dispose();
            JOptionPane.showMessageDialog(null, "Outlet Berhasil Ditambah, Silahkan Refresh!", "Pesan Dari Admin", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldAlamatOutlet = new textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTeleponOutlet = new textfield.TextField();
        titlePelanggan = new javax.swing.JLabel();
        buttonPerbarui = new com.k33ptoo.components.KButton();
        fieldIDOutlet = new textfield.TextField();
        fieldNamaOutlet = new textfield.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Outlet");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fieldAlamatOutlet.setLabelText("Alamat");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laundry image/outlet.png"))); // NOI18N

        fieldTeleponOutlet.setLabelText("Telepon");

        titlePelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePelanggan.setText("Tambah Outlet");

        buttonPerbarui.setText("Tambah");
        buttonPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPerbarui.setIconTextGap(5);
        buttonPerbarui.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkBorderRadius(12);
        buttonPerbarui.setkEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buttonPerbarui.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkPressedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkSelectedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkStartColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerbaruiActionPerformed(evt);
            }
        });

        fieldIDOutlet.setLabelText("ID Outlet");
        fieldIDOutlet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldIDOutletMouseClicked(evt);
            }
        });

        fieldNamaOutlet.setLabelText("Nama Outlet");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIDOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAlamatOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonPerbarui, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldTeleponOutlet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(titlePelanggan)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titlePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldIDOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldAlamatOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldTeleponOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerbaruiActionPerformed
     insertData();

    }//GEN-LAST:event_buttonPerbaruiActionPerformed

    private void fieldIDOutletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldIDOutletMouseClicked
        JOptionPane.showMessageDialog(null, "ID Outlet dibuat secara otomatis dan tidak bisa diedit", "From Admin", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_fieldIDOutletMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahOutlet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.k33ptoo.components.KButton buttonPerbarui;
    public static textfield.TextField fieldAlamatOutlet;
    public static textfield.TextField fieldIDOutlet;
    public static textfield.TextField fieldNamaOutlet;
    public static textfield.TextField fieldTeleponOutlet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel titlePelanggan;
    // End of variables declaration//GEN-END:variables
}
