/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package outlet;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import static outlet.TambahOutlet.fieldAlamatOutlet;
import static outlet.TambahOutlet.fieldIDOutlet;
import static outlet.TambahOutlet.fieldNamaOutlet;
import static outlet.TambahOutlet.fieldTeleponOutlet;

/**
 *
 * @author Kahfi
 */
public class UpdateOutlet extends javax.swing.JFrame {
    String idOutlet, namaOutlet, alamatOutlet, teleponOutlet;
    Connection con;
    PreparedStatement pst;
    ResultSet set;
    koneksi koneksi = new koneksi();

    /**
     * Creates new form UpdateForm
     */
    public UpdateOutlet() {
        initComponents();
    }
    
      public void komponen() {
        this.idOutlet = fieldIDOutlet.getText();
        this.namaOutlet = fieldNamaOutlet.getText();
        this.alamatOutlet = fieldAlamatOutlet.getText();
        this.teleponOutlet = fieldTeleponOutlet.getText();
    }
      
    public void updateOutlet(){
        komponen();
        try {
            String sql = "update tb_outlet set nama ='" + namaOutlet + "', alamat = '" + alamatOutlet + "', tlp = '" + teleponOutlet + "' where id_outlet = '" + idOutlet + "'"; 
            this.pst = koneksi.getKoneksi().prepareStatement(sql);
            pst.execute(); 
            this.dispose();
            JOptionPane.showMessageDialog(null, "Outlet Berhasil DiUpdate, Silahkan Refresh!", "Pesan Dari Admin", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void hapusOutlet(){
        komponen(); 
        try {
            String sql = "delete from tb_outlet where id_outlet ='" + idOutlet + "'"; 
            this.pst = koneksi.getKoneksi().prepareStatement(sql); 
            pst.execute(); 
            this.dispose(); 
            JOptionPane.showMessageDialog(null, "Outlet Berhasil Dihapus, Silahkan Refresh!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldNamaOutlet = new textfield.TextField();
        fieldIDOutlet = new textfield.TextField();
        buttonPerbarui = new com.k33ptoo.components.KButton();
        titlePelanggan = new javax.swing.JLabel();
        fieldTeleponOutlet = new textfield.TextField();
        jLabel2 = new javax.swing.JLabel();
        fieldAlamatOutlet = new textfield.TextField();
        buttonPerbarui1 = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Update Outlet");
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        fieldNamaOutlet.setLabelText("Nama Outlet");

        fieldIDOutlet.setLabelText("ID Outlet");
        fieldIDOutlet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fieldIDOutletMouseClicked(evt);
            }
        });

        buttonPerbarui.setText("Update");
        buttonPerbarui.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPerbarui.setIconTextGap(5);
        buttonPerbarui.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkBorderRadius(12);
        buttonPerbarui.setkEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buttonPerbarui.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui.setkPressedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkSelectedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.setkStartColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerbaruiActionPerformed(evt);
            }
        });

        titlePelanggan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titlePelanggan.setText("Update Outlet");

        fieldTeleponOutlet.setLabelText("Telepon");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Laundry image/outlet.png"))); // NOI18N

        fieldAlamatOutlet.setLabelText("Alamat");

        buttonPerbarui1.setText("Hapus");
        buttonPerbarui1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPerbarui1.setIconTextGap(5);
        buttonPerbarui1.setkBackGroundColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui1.setkBorderRadius(12);
        buttonPerbarui1.setkEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui1.setkHoverEndColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui1.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buttonPerbarui1.setkHoverStartColor(new java.awt.Color(102, 102, 255));
        buttonPerbarui1.setkPressedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui1.setkSelectedColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui1.setkStartColor(new java.awt.Color(153, 153, 255));
        buttonPerbarui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPerbarui1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldIDOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldAlamatOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTeleponOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonPerbarui1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(titlePelanggan)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titlePelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldIDOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldNamaOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldAlamatOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(fieldTeleponOutlet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPerbarui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPerbarui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldIDOutletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldIDOutletMouseClicked
        JOptionPane.showMessageDialog(null, "ID Outlet dibuat secara otomatis dan tidak bisa diedit", "From Admin", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_fieldIDOutletMouseClicked

    private void buttonPerbaruiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerbaruiActionPerformed
        updateOutlet();
    }//GEN-LAST:event_buttonPerbaruiActionPerformed

    private void buttonPerbarui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPerbarui1ActionPerformed
      komponen();
      int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin menghapus : " + namaOutlet, "Pesan dari Admin", JOptionPane.WARNING_MESSAGE); 
      if(konfirmasi==0){
          hapusOutlet();
      }
              
    }//GEN-LAST:event_buttonPerbarui1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateOutlet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateOutlet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static com.k33ptoo.components.KButton buttonPerbarui;
    public static com.k33ptoo.components.KButton buttonPerbarui1;
    public static textfield.TextField fieldAlamatOutlet;
    public static textfield.TextField fieldIDOutlet;
    public static textfield.TextField fieldNamaOutlet;
    public static textfield.TextField fieldTeleponOutlet;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel titlePelanggan;
    // End of variables declaration//GEN-END:variables
}
